apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mb-qa-client.fullname" . }}
  labels:
    {{- include "mb-qa-client.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "mb-qa-client.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
    - port: {{ .Values.service.targetPort }}
      protocol: TCP