export const users = [
  {
    id: 1,
    name: "Sara Zane",
    department: "ITP/ID",
    email: "example@mercedes-benz.com",
    img: "https://mdbcdn.b-cdn.net/img/new/avatars/10.webp",
    joining: "Nov 2022",
    questions: "203",
    light: "1202",
    tags: ["ReactJS", "Redux-Toolkit"],
    badges: {
      gold: 86,
      silver: 30,
      bronze: 23,
    },
  },
  {
    id: 2,
    name: "Mathew Stube",
    department: "ITP/ID",
    email: "example@mercedes-benz.com",
    img: "https://mdbcdn.b-cdn.net/img/new/avatars/2.webp",
    joining: "Oct 2022",
    questions: "11",
    light: "188",
    tags: ["ReactJS", "Tailwind"],
    badges: {
      gold: 86,
      silver: 30,
      bronze: 23,
    },
  },
  {
    id: 3,
    name: "Michel Richerd",
    department: "ITP/ID",
    email: "example@mercedes-benz.com",
    img: "https://mdbcdn.b-cdn.net/img/new/avatars/3.webp",
    joining: "May 2022",
    questions: "90",
    light: "87",
    tags: ["Java", "Spring-Boot"],
    badges: {
      gold: 86,
      silver: 30,
      bronze: 23,
    },
  },
  {
    id: 4,
    name: "Dan Harrise",
    department: "ITP/ID",
    email: "example@mercedes-benz.com",
    img: "https://mdbcdn.b-cdn.net/img/new/avatars/4.webp",
    joining: "Dec 2022",
    questions: "100",
    light: "29",
    tags: ["ReactJS", "Redux-Toolkit", "CSS"],
    badges: {
      gold: 86,
      silver: 30,
      bronze: 23,
    },
  },
  {
    id: 5,
    name: "Jennifer Kon",
    department: "ITP/ID",
    email: "example@mercedes-benz.com",
    img: "https://mdbcdn.b-cdn.net/img/new/avatars/5.webp",
    joining: "Jan 2023",
    questions: "39",
    light: "8",
    tags: ["ReactJS", "Redux Toolkit", "Material-UI"],
    badges: {
      gold: 86,
      silver: 30,
      bronze: 23,
    },
  },
];
